import { NextResponse } from "next/server";
import { PortfolioAllocationModel } from "@/models/PortfolioAllocation";

const portfolio = {
  id: 1,
  user_id: 1,
  name: "Hisse Senedi Portfoyum",
  description: null,
  created_at: Date.now(),
  updated_at: Date.now() + 2,
  portfolioAllocations: [
    {
      id: 1,
      portfolio_id: 1,
      asset: {
        id: 1,
        name: "APPL",
      },
      target_percentage: 20,
      current_percentage: 20.1,
      amount: 200,
    },
    {
      id: 2,
      portfolio_id: 1,
      asset: {
        id: 2,
        name: "SP500",
      },
      target_percentage: 30,
      current_percentage: 29.9,
    },
    {
      id: 3,
      portfolio_id: 1,
      asset: {
        id: 3,
        name: "MTV",
      },
      target_percentage: 10,
      current_percentage: 5,
      amount: 200,
    },
    {
      id: 4,
      portfolio_id: 1,
      asset: {
        id: 4,
        name: "EUR",
      },
      target_percentage: 5,
      current_percentage: 10,
      amount: 200,
    },
    {
      id: 5,
      portfolio_id: 1,
      asset: {
        id: 5,
        name: "HEPS",
      },
      target_percentage: 5,
      current_percentage: 5,
      amount: 200,
    },
    {
      id: 6,
      portfolio_id: 1,
      asset: {
        id: 6,
        name: "USD",
      },
      target_percentage: 20,
      current_percentage: 9,
      amount: 200,
    },
    {
      id: 7,
      portfolio_id: 1,
      asset: {
        id: 7,
        name: "GOLD g",
      },
      target_percentage: 2,
      current_percentage: 13,
      amount: 200,
    },
    {
      id: 8,
      portfolio_id: 1,
      asset: {
        id: 8,
        name: "ALPHABET",
      },
      target_percentage: 2,
      current_percentage: 1,
      amount: 200,
    },
    {
      id: 9,
      portfolio_id: 1,
      asset: {
        id: 9,
        name: "META",
      },
      target_percentage: 2,
      current_percentage: 4,
      amount: 200,
    },
    {
      id: 10,
      portfolio_id: 1,
      asset: {
        id: 10,
        name: "NVIDIA",
      },
      target_percentage: 4,
      current_percentage: 3,
      amount: 200,
    },
    {
      id: 1,
      portfolio_id: 1,
      asset: {
        id: 1,
        name: "APPL",
      },
      target_percentage: 20,
      current_percentage: 20.1,
      amount: 200,
    },
    {
      id: 2,
      portfolio_id: 1,
      asset: {
        id: 2,
        name: "SP500",
      },
      target_percentage: 30,
      current_percentage: 29.9,
    },
    {
      id: 3,
      portfolio_id: 1,
      asset: {
        id: 3,
        name: "MTV",
      },
      target_percentage: 10,
      current_percentage: 5,
      amount: 200,
    },
    {
      id: 4,
      portfolio_id: 1,
      asset: {
        id: 4,
        name: "EUR",
      },
      target_percentage: 5,
      current_percentage: 10,
      amount: 200,
    },
    {
      id: 5,
      portfolio_id: 1,
      asset: {
        id: 5,
        name: "HEPS",
      },
      target_percentage: 5,
      current_percentage: 5,
      amount: 200,
    },
    {
      id: 6,
      portfolio_id: 1,
      asset: {
        id: 6,
        name: "USD",
      },
      target_percentage: 20,
      current_percentage: 9,
      amount: 200,
    },
    {
      id: 7,
      portfolio_id: 1,
      asset: {
        id: 7,
        name: "GOLD g",
      },
      target_percentage: 2,
      current_percentage: 13,
      amount: 200,
    },
    {
      id: 8,
      portfolio_id: 1,
      asset: {
        id: 8,
        name: "ALPHABET",
      },
      target_percentage: 2,
      current_percentage: 1,
      amount: 200,
    },
    {
      id: 9,
      portfolio_id: 1,
      asset: {
        id: 9,
        name: "META",
      },
      target_percentage: 2,
      current_percentage: 4,
      amount: 200,
    },
    {
      id: 10,
      portfolio_id: 1,
      asset: {
        id: 10,
        name: "NVIDIA",
      },
      target_percentage: 4,
      current_percentage: 3,
      amount: 200,
    },
  ],
  transactions: [
    {
      id: "1",
      portfolio_id: "1",
      asset_id: "1",
      transaction_type: "BUY",
      quantity: 10,
      price_per_unit: 150,
      transaction_date: new Date("2023-01-15"),
    },
    {
      id: "2",
      portfolio_id: "1",
      asset_id: "2",
      transaction_type: "BUY",
      quantity: 15,
      price_per_unit: 200,
      transaction_date: new Date("2023-01-20"),
    },
    {
      id: "3",
      portfolio_id: "1",
      asset_id: "3",
      transaction_type: "BUY",
      quantity: 5,
      price_per_unit: 100,
      transaction_date: new Date("2023-01-25"),
    },
    {
      id: "4",
      portfolio_id: "1",
      asset_id: "4",
      transaction_type: "BUY",
      quantity: 2,
      price_per_unit: 50,
      transaction_date: new Date("2023-01-30"),
    },
    {
      id: "5",
      portfolio_id: "1",
      asset_id: "5",
      transaction_type: "BUY",
      quantity: 3,
      price_per_unit: 75,
      transaction_date: new Date("2023-02-05"),
    },
    {
      id: "6",
      portfolio_id: "1",
      asset_id: "6",
      transaction_type: "BUY",
      quantity: 10,
      price_per_unit: 180,
      transaction_date: new Date("2023-02-10"),
    },
    {
      id: "7",
      portfolio_id: "1",
      asset_id: "7",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 30,
      transaction_date: new Date("2023-02-15"),
    },
    {
      id: "8",
      portfolio_id: "1",
      asset_id: "8",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 40,
      transaction_date: new Date("2023-02-20"),
    },
    {
      id: "9",
      portfolio_id: "1",
      asset_id: "9",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 35,
      transaction_date: new Date("2023-02-25"),
    },
    {
      id: "10",
      portfolio_id: "1",
      asset_id: "10",
      transaction_type: "BUY",
      quantity: 2,
      price_per_unit: 60,
      transaction_date: new Date("2023-03-01"),
    },
    {
      id: "11",
      portfolio_id: "1",
      asset_id: "1",
      transaction_type: "BUY",
      quantity: 5,
      price_per_unit: 155,
      transaction_date: new Date("2023-03-05"),
    },
    {
      id: "12",
      portfolio_id: "1",
      asset_id: "2",
      transaction_type: "SELL",
      quantity: 3,
      price_per_unit: 210,
      transaction_date: new Date("2023-03-10"),
    },
    {
      id: "13",
      portfolio_id: "1",
      asset_id: "3",
      transaction_type: "BUY",
      quantity: 2,
      price_per_unit: 105,
      transaction_date: new Date("2023-03-15"),
    },
    {
      id: "14",
      portfolio_id: "1",
      asset_id: "4",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 52,
      transaction_date: new Date("2023-03-20"),
    },
    {
      id: "15",
      portfolio_id: "1",
      asset_id: "5",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 80,
      transaction_date: new Date("2023-03-25"),
    },
    {
      id: "16",
      portfolio_id: "1",
      asset_id: "6",
      transaction_type: "BUY",
      quantity: 5,
      price_per_unit: 185,
      transaction_date: new Date("2023-03-30"),
    },
    {
      id: "17",
      portfolio_id: "1",
      asset_id: "7",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 32,
      transaction_date: new Date("2023-04-05"),
    },
    {
      id: "18",
      portfolio_id: "1",
      asset_id: "8",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 42,
      transaction_date: new Date("2023-04-10"),
    },
    {
      id: "19",
      portfolio_id: "1",
      asset_id: "9",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 36,
      transaction_date: new Date("2023-04-15"),
    },
    {
      id: "20",
      portfolio_id: "1",
      asset_id: "10",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 62,
      transaction_date: new Date("2023-04-20"),
    },
    {
      id: "21",
      portfolio_id: "1",
      asset_id: "1",
      transaction_type: "SELL",
      quantity: 2,
      price_per_unit: 160,
      transaction_date: new Date("2023-04-25"),
    },
    {
      id: "22",
      portfolio_id: "1",
      asset_id: "2",
      transaction_type: "BUY",
      quantity: 8,
      price_per_unit: 205,
      transaction_date: new Date("2023-04-30"),
    },
    {
      id: "23",
      portfolio_id: "1",
      asset_id: "3",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 110,
      transaction_date: new Date("2023-05-05"),
    },
    {
      id: "24",
      portfolio_id: "1",
      asset_id: "4",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 53,
      transaction_date: new Date("2023-05-10"),
    },
    {
      id: "25",
      portfolio_id: "1",
      asset_id: "5",
      transaction_type: "BUY",
      quantity: 2,
      price_per_unit: 78,
      transaction_date: new Date("2023-05-15"),
    },
    {
      id: "26",
      portfolio_id: "1",
      asset_id: "6",
      transaction_type: "SELL",
      quantity: 3,
      price_per_unit: 190,
      transaction_date: new Date("2023-05-20"),
    },
    {
      id: "27",
      portfolio_id: "1",
      asset_id: "7",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 33,
      transaction_date: new Date("2023-05-25"),
    },
    {
      id: "28",
      portfolio_id: "1",
      asset_id: "8",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 41,
      transaction_date: new Date("2023-05-30"),
    },
    {
      id: "29",
      portfolio_id: "1",
      asset_id: "9",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 37,
      transaction_date: new Date("2023-06-05"),
    },
    {
      id: "30",
      portfolio_id: "1",
      asset_id: "10",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 63,
      transaction_date: new Date("2023-06-10"),
    },
    {
      id: "31",
      portfolio_id: "1",
      asset_id: "1",
      transaction_type: "BUY",
      quantity: 3,
      price_per_unit: 158,
      transaction_date: new Date("2023-06-15"),
    },
    {
      id: "32",
      portfolio_id: "1",
      asset_id: "2",
      transaction_type: "BUY",
      quantity: 5,
      price_per_unit: 208,
      transaction_date: new Date("2023-06-20"),
    },
    {
      id: "33",
      portfolio_id: "1",
      asset_id: "3",
      transaction_type: "BUY",
      quantity: 2,
      price_per_unit: 107,
      transaction_date: new Date("2023-06-25"),
    },
    {
      id: "34",
      portfolio_id: "1",
      asset_id: "4",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 54,
      transaction_date: new Date("2023-06-30"),
    },
    {
      id: "35",
      portfolio_id: "1",
      asset_id: "5",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 79,
      transaction_date: new Date("2023-07-05"),
    },
    {
      id: "36",
      portfolio_id: "1",
      asset_id: "6",
      transaction_type: "BUY",
      quantity: 4,
      price_per_unit: 187,
      transaction_date: new Date("2023-07-10"),
    },
    {
      id: "37",
      portfolio_id: "1",
      asset_id: "7",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 34,
      transaction_date: new Date("2023-07-15"),
    },
    {
      id: "38",
      portfolio_id: "1",
      asset_id: "8",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 40,
      transaction_date: new Date("2023-07-20"),
    },
    {
      id: "39",
      portfolio_id: "1",
      asset_id: "9",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 36,
      transaction_date: new Date("2023-07-25"),
    },
    {
      id: "40",
      portfolio_id: "1",
      asset_id: "10",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 64,
      transaction_date: new Date("2023-07-30"),
    },
    {
      id: "41",
      portfolio_id: "1",
      asset_id: "1",
      transaction_type: "BUY",
      quantity: 2,
      price_per_unit: 159,
      transaction_date: new Date("2023-08-05"),
    },
    {
      id: "42",
      portfolio_id: "1",
      asset_id: "2",
      transaction_type: "SELL",
      quantity: 2,
      price_per_unit: 212,
      transaction_date: new Date("2023-08-10"),
    },
    {
      id: "43",
      portfolio_id: "1",
      asset_id: "3",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 108,
      transaction_date: new Date("2023-08-15"),
    },
    {
      id: "44",
      portfolio_id: "1",
      asset_id: "4",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 52,
      transaction_date: new Date("2023-08-20"),
    },
    {
      id: "45",
      portfolio_id: "1",
      asset_id: "5",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 81,
      transaction_date: new Date("2023-08-25"),
    },
    {
      id: "46",
      portfolio_id: "1",
      asset_id: "6",
      transaction_type: "BUY",
      quantity: 3,
      price_per_unit: 188,
      transaction_date: new Date("2023-08-30"),
    },
    {
      id: "47",
      portfolio_id: "1",
      asset_id: "7",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 31,
      transaction_date: new Date("2023-09-05"),
    },
    {
      id: "48",
      portfolio_id: "1",
      asset_id: "8",
      transaction_type: "SELL",
      quantity: 1,
      price_per_unit: 43,
      transaction_date: new Date("2023-09-10"),
    },
    {
      id: "49",
      portfolio_id: "1",
      asset_id: "9",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 35,
      transaction_date: new Date("2023-09-15"),
    },
    {
      id: "50",
      portfolio_id: "1",
      asset_id: "10",
      transaction_type: "BUY",
      quantity: 1,
      price_per_unit: 61,
      transaction_date: new Date("2023-09-20"),
    },
  ],
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const portfolioId = searchParams.get("portfolioId");

  if (!portfolioId) {
    return new NextResponse(
      JSON.stringify({ error: "Portfolio ID is required" }),
      {
        status: 400,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      },
    );
  }

  return new NextResponse(JSON.stringify(portfolio), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
    },
  });

  // try {
  //   const allocations =
  //     await PortfolioAllocationModel.getPortfolioAllocations(portfolioId);
  //   return NextResponse.json(allocations);
  // } catch (error) {
  //   console.error("Error fetching portfolio allocations:", error);
  //   return NextResponse.json(
  //     { error: "Internal Server Error" },
  //     { status: 500 },
  //   );
  // }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const newAllocation = await PortfolioAllocationModel.create(body);
    return NextResponse.json(newAllocation, { status: 201 });
  } catch (error) {
    console.error("Error creating portfolio allocation:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
